name: Build release APK

on:
  workflow_dispatch:
  push:
    branches:
      - 15-testing

jobs:
  build-release-apk:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: 21
      - uses: gradle/actions/setup-gradle@v4
        with:
          gradle-home-cache-cleanup: true
      - name: Write sign info
        run: |
            echo "${{ secrets.KEYSTORE }}" | base64 -d > ${{ github.workspace }}/key.jks
            echo storeFile='${{ github.workspace }}/key.jks' >> keystore.properties
            echo storePassword='${{ secrets.KEYSTORE_PASSWORD }}' >> keystore.properties
            echo keyAlias='${{ secrets.KEY_ALIAS }}' >> keystore.properties
            echo keyPassword='${{ secrets.KEY_PASSWORD }}' >> keystore.properties
      - name: Build release APK
        run: ./gradlew assembleLawnWithQuickstepGithubRelease
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: Release APK
          path: build/outputs/apk/lawnWithQuickstepGithub/release/*.apk
          
